blog/urls.py
from django.conf.urls import patterns, include, url
urlpatterns = patterns('',
                       url(r'^$', 'blog.views.muestrainicio', name='Inicio' ),
                       url(r'^ver_post/(?P<id_post>[0-9]+)/$', 'blog.views.ver_post', name='vermipost'),
                       url(r'^botonloco/$', 'blog.views.verbtnmg', name='Boton Loco' ),
                       url(r'^calculadora/$', 'blog.views.vercal', name='Calculadora' ),
                       url(r'^conversor/$', 'blog.views.verconv', name='Conversor' ),
                       url(r'^cronometro/$', 'blog.views.vercro', name='Cronometro' ),
                       url(r'^Imagenes/$', 'blog.views.verimagen', name='Imagenes' ),
                       url(r'^comentarios/$', 'blog.views.vernoticias', name='Comentarios' ),
                       url(r'^Personal/$', 'blog.views.mostrarper', name='Personal' ),
                      )

pag/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from pag import settings
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('blog.urls', namespace = "nano")),
    url(r'^admin/', include(admin.site.urls)),    
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
# -*- coding: utf-8 -*-
from django.db import models

class Entrada(models.Model):
    class Meta:
        verbose_name = "Mi Entrada"
        verbose_name_plural = "Todas mis entradas"
        ordering=['-fecha']

    titulo = models.CharField(u'Titulo', max_length=100)
    fecha = models.DateTimeField(u'Fecha del Post',auto_now_add=True)
    resumen= models.CharField(u'Resumen',max_length=512)
    contenido = models.TextField(u'Contenido')
    

    def __str__(self):
        return self.titulo


    

blog/views.py
from django.template import RequestContext
from django.shortcuts import render
from django.shortcuts import render_to_response, render, redirect
from blog.models import Entrada 

import os

def muestrainicio(request):
    return render_to_response('Inicio.html',
                              {},
                              RequestContext(request))
def verbtnmg(request):
    return render_to_response('cambiolugar.html',
                              {},
                              RequestContext(request))
def mostrarper(request):
    return render_to_response('personal.html',
                              {},
                              RequestContext(request))
def vercal(request):
    return render_to_response('Calculadora.html',
                              {},
                              RequestContext(request))
def verconv(request):
    return render_to_response('conversor.html',
                              {},
                              RequestContext(request))
def vercro(request):
    return render_to_response('cronometro.html',
                              {},
                              RequestContext(request))
def verimagen(request):
    return render_to_response('Imagenes.html',{},RequestContext(request))

def vernoticias(request):
    context = RequestContext(request)
    posts = Entrada.objects.all()
    return render_to_response('comentarios.html',{'posts':posts},context)

def ver_post(request, id_post):
    context = RequestContext(request)
    mi_post = Entrada.objects.get(id=id_post)
    return render_to_response('post.html',{'post':mi_post},context)

blog/templates/Calculadora.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block contenido %}
<html>
    <head>
        <style>
            body{
                background: white;
                text-align: center;
            }
            
            h1{
                border: white;
            }
            
.button {
  border-radius: 4px;
  background-color: black;
  border: none;
  color: white;
  text-align: center;
  font-size: 28px;
  padding: 20px;
  width: 200px;
  margin: 5px;
    align-content: center;
    
}
            h1{
                color: black;
            }
        
        
        </style>
<br>
        <br>
        <br>
        <body class="red">
            <br>

        
<h1 id="poenele">0</h1>


<button class="button" id="num1" onclick=addNum(1)>1</button>
<button class="button" id="num1" onclick=addNum(2)>2</button>
<button class="button" id="num1" onclick=addNum(3)>3</button>
<br>
<button class="button" id="num1" onclick=addNum(4)>4</button>
<button class="button" id="num1" onclick=addNum(5)>5</button>
<button class="button" id="num1" onclick=addNum(6)>6</button>
<br>
<button class="button" id="num1" onclick=addNum(7)>7</button>
<button class="button" id="num1" onclick=addNum(8)>8</button>
<button class="button" id="num1" onclick=addNum(9)>9</button>
<br>
<button class="button" id="num1" onclick=addNum(0)>0</button>
<button class="button" id="op" onclick=addNum("+")>+</button>
<button class="button" id="op" onclick=addNum("-")>-</button>
<br>
<button class="button" id="op" onclick=addNum("*")>*</button>
<button class="button" id="op" onclick=addNum("/")>/</button>
<button class="button" id="nop" onclick=igualar()>=</button>
<button class="button" id="op" onclick=borrar()>C</button>
    
<script>

    function addNum(num){
        var num1 = num;
        var num2 = document.getElementById("poenele").innerHTML;
        var display = num2 + num1;
        document.getElementById("poenele").innerHTML = display;
        console.log(display);
        }
    function igualar(){
        var num2 = document.getElementById("poenele").innerHTML;
        var res = eval(num2);
        document.getElementById("poenele").innerHTML = res;
        }
    
    
    function borrar(){
        var num2 = document.getElementById("poenele").innerHTML;
        var res = eval(0)
        document.getElementById("poenele").innerHTML = res;

        
        
    }
</script>
        </body>
            </head>
</html>


{% endblock %}

blog/templates/Imagenes.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block contenido %}

<html>	
    <head>
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>

        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <!-----------------------------------------------| IMPORTAR |-------------------------------------------------------------->
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <link rel="stylesheet" href="materialize/css/materialize.css">
        <title>Inicio</title>
    </head>
    <style>
img{
width:100%;
max-width:600px;
}


#myProgress {
  text-align: center;
  position: relative;
  width: 100%;
  height: 20px;
  background-color: white;
  align-self: center;  
    position: fixed;
    
}

#myBar {
  text-align: center;
  position: center;
  width: 80%;
  height: 100%;
  background-color: black;
  align-self: center; 

}
</style>
    
<body onload="cambiar()" class="red">

        <!-----------------------------------------------| IMPORTAR JS |-------------------------------------------------------------->
        <script type="text/javascript" src="js/jquery-1.11.3.js"></script>
        <script type="text/javascript" src="js/materialize.min.js"></script>
        <!-----------------------------------------------| IMPORTAR JS |-------------------------------------------------------------->

            <ul id='dropdown1' class='dropdown-content'>
            <li><a href="Image.html">Galeria</a></li>
            <li class="divider"></li>
            <li><a href="cronometro.html">Cronometro</a></li>
            <li class="divider"></li>
            <li><a href="conversor.html">Conversor de Moneda</a></li>
            <li class="divider"></li>
            <li><a href="boton_magico.html">Boton Troll</a></li>
            <li class="divider"></li>
            <li><a href="Calculadora.html">Calculadora</a></li>
            </ul>
    </div>
        </nav>
<br>
<br>
<br>
<div class="center">
 <img src="/static/img/imagen1.jpg" id="imagen">
    <br>
    <br>
    
<div id="myProgress">
<div id="myBar"></div>
</div>  
 <script>
     var elem = document.getElementById("myBar"); 
    var width = 1;
    var id = setInterval(frame, 5);
    function frame() {
        if (width >= 100) {
            cambiarImagenes();
            width=0;
        } else {
            width+= 0.1;
            elem.style.width = width + '%'; 
        }
    }
     var imagenes=[
        '/static/img/imagen1.jpg',
        '/static/img/imagen2.jpg',
        '/static/img/imagen3.jpg',
        '/static/img/imagen4.jpg',

        ];
     function cambiarImagenes()
     
    {
 
        var index=Math.floor((Math.random()*imagenes.length));
         document.getElementById("imagen").src=imagenes[index];
    }
  

</script>
{% endblock %}

blog/templates/Inicio.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block contenido %}


<html>	
    <head>
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="/static/css/materialize.css"  media="screen,projection"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <!-----------------------------------------------| IMPORTAR |-------------------------------------------------------------->
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <link rel="stylesheet" href="/static/css/materialize.css">
        
       <div class="center-align">
            <body class="red">

                <script type="text/javascript" src="js/jquery-1.11.3.js"></script>
                <script type="text/javascript" src="js/materialize.js"></script>
                <br>
                <br>
<h1><center><font face="KG Sorry Not Sorry" size="9">Tomas Larguro</font><br/></center></h1>
                
		<img src="/static/img/portada.png" height="400" width="700"> <br>
                    <p><center><font face="Watermak" size="3">.“No soy un ciclista sólo en el sentido de que viajo en bicicleta, lo soy en el mismo sentido en que algunas personas son socialistas, fundamentalistas cristianos o realistas éticos; es decir el ciclismo es mi ideología, un sistema de creencia sobre la base de la pureza y la economía de movimiento y generosidad con el ambiente… y quiero convertir a otros”. Robert Hanks.</font>s<br/></center></p>

                <br>
                
                

                <h1><center><font face="KG Sorry Not Sorry" size="9">Michael Phelps</font><br/></center></h1>
                                		<img src="/static/img/michael.png" height="400" width="700"> <br>

                    <p><center><font face="Watermak" size="3">"Tengo la oportunidad de ser parte de la historia de la natación. Llevar el deporte a un nuevo nivel sería un honor para mí. No hay mejor momento para intentar esto que ahora."</font><br/></center></p>
                
                           
                <h1><center><font face="KG Sorry Not Sorry" size="9">Ginobili</font><br/></center></h1>
                                                		<img src="/static/img/manu.png" height="400" width="700"> <br>

                    <p><center><font face="Watermak" size="3">"No preguntes qué puede hacer por ti el equipo. Pregunta qué puedes hacer tú por él"</font><br/></center></p>


                
                
                

                    </div>
            
{% endblock %}

blog/templates/base.html
{% load staticfiles %}
<html>	
    <head>

        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>

        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <title>Nano Blog</title>
    </head>

    <body class="red" style="overflow-x:hidden">

        <script type="text/javascript" src="{% static 'js/jquery-1.11.3.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>

        <nav class="grey darken-4" style='text-align:center;'>
            <div class="nav-wrapper" >
            
            <font face="FunSized" size="7">Nano Blog</font>
            <br />
            <div >
                <ul style='margin-left:15%;width:100%;'>
                    <li><a href="{% url 'nano:Inicio' %}">Inicio</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'nano:Imagenes' %}">Galeria de Imagenes</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'nano:Cronometro' %}">Cronometro</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'nano:Conversor' %}">Conversor</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'nano:Boton Loco' %}">Formulario</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'nano:Calculadora' %}">Calculadora</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'nano:Comentarios' %}">Comentarios</a></li>    
                    <li><a href="{% url 'nano:Personal' %}">Perosnal</a></li>           
                </ul>
            </div>
            </div>
        </nav>
        
         {% block contenido %}
        {% endblock %}

        
       
        <style>
            nav {
                height: 20%;
                line-height: 56px;
            }
        </style>

    </body>
</html>

blog/templates/cambiolugar.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block contenido %}

<html>
    <body class="red">

        <divA>
<br>
<br>
            <br>
    <label for="fname">Nombre:</label>
    <input type="text" id="fname" name="firstname">
            <br>

    <label for="lname">Apellido:</label>
    <input type="text" id="lname" name="lastname">
            <br>

    <label for="country">Provincia:</label>
    <select id="country" name="country">
      <option value="australia">Cordoba</option>
      <option value="canada">Salta</option>
      <option value="usa">Formosa</option>
          <option value="usa">Naci en la nada</option>

    </select>
  <br>
            <br>
            <br>
            <br>
  <div id="queonda" onmouseover="mover()"><h1>Siguiente!</h1></div>

</divA>
<style>
    label{
        color:black;
        font-size: 20px;
        border-left: 50;
            margin-left: 1%;

        
    }    
    
    #queonda {
    position: fixed;
    font-size: 10px;
color:black;
    width: 50;
    height: 1;
    text-align: center;
    border-radius: 12px;
}

input[type=text], select {
    width: 70%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid black;
    border-radius: 4px;
    box-sizing: border-box;
    margin-left: 1%;
    }
    
    
divA {
    border-radius: 5px;
    padding: 40px;
}

</style>    
 
        

<script>
function mover() {
        var div = document.getElementById("queonda");
        var a = Math.random();
        var a = a*1000;
        var b = Math.random();
        var b = b*600;
        console.log(a);
        div.style.left = a;
        div.style.top = b;
}
    
    
</script>
    </body>
{% endblock %}

blog/templates/comentarios.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block contenido %}
<html>	
    <head>
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="/static/css/materialize.css"  media="screen,projection"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <!-----------------------------------------------| IMPORTAR |-------------------------------------------------------------->
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <link rel="stylesheet" href="/static/css/materialize.css">
        <div class="center-align">
            </head>
        <body class="red">
            <br>
            <br>

            {% for post in posts %}
            <div class="post-preview">
                <a href="{% url 'nano:vermipost' post.id %}">
                    <h2 class="post-title">
                        {{post.titulo}}
                    </h2>
                    <h3 class="post-subtitle">
                        {{post.resumen}}
                    </h3>
                            		<img src="/static/img/separador.png"> <br>

                </a>
            </div>
            {% endfor %}

            <script type="text/javascript" src="js/jquery-1.11.3.js"></script>
            <script type="text/javascript" src="js/materialize.js"></script>
        </body>
{% endblock %}  

blog/templates/conversor.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block contenido %}
<html>	
    <head>
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <!-----------------------------------------------| IMPORTAR |-------------------------------------------------------------->
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <link rel="stylesheet" href="materialize/css/materialize.css">
        <title>Inicio</title>
        <!-----------------------------------------------| IMPORTAR JS |-------------------------------------------------------------->
        <script type="text/javascript" src="js/jquery-1.11.3.js"></script>
        <script type="text/javascript" src="js/materialize.min.js"></script>
        <!-----------------------------------------------| IMPORTAR JS |-------------------------------------------------------------->
    </head>
    <body class="red">
        <ul id='dropdown1' class='dropdown-content'>

            <li><a href="Image.html">Galeria</a></li>
            <li class="divider"></li>
            <li><a href="cronometro.html">Cronometro</a></li>
            <li class="divider"></li>
            <li><a href="conversor.html">Conversor de Moneda</a></li>
            <li class="divider"></li>
            <li><a href="boton_magico.html">Boton Troll</a></li>
            <li class="divider"></li>
            <li><a href="Calculadora.html">Calculadora</a></li>

        </ul>
              <br>
        <br>
        <div class="container">
            <div>
                De<select id="tipoMoneda" class="col l5 offset-l1"> 
                <option selected>Seleccionar Tipo de Moneda</option>
                <option value="1">Pesos Argentinos </option> 
                <option value="2">Dolares </option> 
                <option value="3">Euros </option> 
                <option value="4">Pesos Uruguayos</option>
                <option value="5">Pesos Chilenos</option></select>
                <input type="text" id="valor" value=""></input>
        </div>
        <div>
            De<select id="TipoMonedaFinal"> 
            <option selected>Seleccionar Tipo de Moneda</option>
            <option value="1">Pesos Argentinos </option> 
            <option value="2">Dolares </option> 
            <option value="3">Euros </option> 
            <option value="4">Pesos Uruguayos</option>
            <option value="5">Pesos Chilenos</option></select>
            <input type="text" id="valorFinal" value=""></input>
        </div>

    <div class="center-align">
        <a type="button" id="botonConvertir" value="Convertir" onclick="cambio()" class="waves-effect waves-light btn">Convertir</a> 
        <a type="button" id="botonLimpiar" value="Limpiar" onclick="limpieza()" class="waves-effect waves-light btn">Limpiar</a>
    </div>
    </div>


<br></br>

</body>
<script>
    function limpieza(){
        document.getElementById("valorFinal").value = "";
        document.getElementById("valor").value = "";
    }
    function cambio(){
        var seleccion1 = document.getElementById("tipoMoneda");
        var valorSeleccion1 =seleccion1.options[seleccion1.selectedIndex].value;

        var seleccion2 = document.getElementById("TipoMonedaFinal"); 
        var valorSeleccion2 = seleccion2.options[seleccion2.selectedIndex].value;
        console.log(valorSeleccion1);
        console.log(valorSeleccion2);
        var valorDivisa=0.0;

        switch(parseInt(valorSeleccion1)) {
            case 1:

                switch(parseInt(valorSeleccion2)) {
                    case 1:
                        valorDivisa=1;
                        break;
                    case 2:
                        valorDivisa=16,9054;
                        break;
                    case 3:
                        valorDivisa=0.10396;
                        break;    
                    case 4:
                        valorDivisa=68.540;
                        break;
                    case 5:
                        valorDivisa=2.9911;
                        break;
                    case 0:
                        alert("Debe Seleccionar una Divisa");
                        break;
                }
                break;
            case 2:
                switch(parseInt(valorSeleccion2)) {
                    case 1:
                        console.log("enter");
                        valorDivisa=8.8968;
                        break;
                    case 2:
                        valorDivisa=1.0;
                        break;
                    case 3:
                        valorDivisa=0.92687;
                        break;    
                    case 4:
                        valorDivisa=609.79;
                        break;
                    case 5:
                        valorDivisa=26.611;
                        break;
                    case 0:
                        alert("Debe Seleccionar una Divisa");
                        break;
                }
                break;
            case 3:
                switch(parseInt(valorSeleccion2)) {
                    case 1:
                        valorDivisa=9.5988;
                        break;
                    case 2:
                        valorDivisa=1,0755;
                        break;
                    case 3:
                        valorDivisa=1;
                        break;    
                    case 4:
                        valorDivisa=657.90;
                        break;
                    case 5:
                        valorDivisa=28.711;
                        break;
                    case 0:
                        alert("Debe Seleccionar una Divisa");
                        break;
                }
                break;    
            case 4:
                switch(parseInt(valorSeleccion2)) {
                    case 1:
                        valorDivisa=0.014590;
                        break;
                    case 2:
                        valorDivisa=0.0016400;
                        break;
                    case 3:
                        valorDivisa=0.0015200;
                        break;    
                    case 4:
                        valorDivisa=1;
                        break;
                    case 5:
                        valorDivisa=0.043640;
                        break;
                    case 0:
                        alert("Debe Seleccionar una Divisa");
                        break;
                }
                break;
            case 5:
                switch(parseInt(valorSeleccion2)) {
                    case 1:
                        valorDivisa=0.33433;
                        break;
                    case 2:
                        valorDivisa=0.037580; 
                        break;
                    case 3:
                        valorDivisa=0.034830;
                        break;    
                    case 4:
                        valorDivisa=22.915;
                        break;
                    case 5:
                        valorDivisa=1;
                        break;
                    case 0:
                        alert("Debe Seleccionar una Divisa");
                        break;
                }
                break;
            case 0:
                alert("Debe Seleccionar una Divisa");
                break;
        }
        var moneda = document.getElementById("valor");
        var resultado = eval(parseFloat(moneda.value)*parseFloat(valorDivisa));
        var MostrarResultado = document.getElementById("valorFinal");
        MostrarResultado.value=resultado;
        console.log(moneda.value+" * "+ valorDivisa+" = "+resultado);
    }
    $(document).ready(function(){
        $("select").material_select()
    });
</script>
</html>        
        
{% endblock %}

blog/templates/personal.html
{% load staticfiles %}
<html>	
    <head>

        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>

        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <title>Nano Blog</title>
    </head>

    <body class="red">

        <script type="text/javascript" src="{% static 'js/jquery-1.11.3.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>

        <nav class="grey darken-4">
            <div class="nav-wrapper" >
                
                <font face="FunSized" size="7" align=left>Nano Blog</font><br/>
    <div class="center">

                <ul class="center hide-on-med-and-down">
           <li><a href="{% url 'nano:Inicio' %}">Inicio</a></li>
            <li class="divider"></li>
                
            <li><a href="{% url 'nano:Imagenes' %}">Galeria de Imagenes</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'nano:Cronometro' %}">Cronometro</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'nano:Conversor' %}">Conversor</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'nano:Boton Loco' %}">Formulario</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'nano:Calculadora' %}">Calculadora</a></li>
                <li class="divider"></li>
            <li><a href="{% url 'nano:Comentarios' %}">Comentarios</a></li>    
            <li><a href="{% url 'nano:Personal' %}">Perosnal</a></li>           
        </ul>
                <br>
        <img src="/static/img/marca.png" height="300" width="310"> <br>

    
        <font face="FunSized" size="7" class= "holi">EN REPARACION...</font><br/>

                
                        </div>
                <style>
                    .holi{
                        color: black;
                    }
                
                </style>
     
        
       
       

    </body>
</html>
            {% block contenido %}
        {% endblock %}

blog/templates/post.html
{% extends 'base.html' %}

{% block contenido %}


<article>
    <div class="container">     
        <br>
        <br>
                <h2 class="section-heading">{{post.titulo}}</h2>
                <h3>{{post.contenido}}</h3>
        <br>
                        <p class="section-heading">{{post.fecha}}</p>
    
    </div>
</article>s
{% endblock %} 